---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-external-tcp
  namespace: networking
  labels:
    app.kubernetes.io/name: ingress-nginx-external
    app.kubernetes.io/part-of: ingress-nginx-external
data:
  "27015": "gaming/cs2:27015"